# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: woocommerce_api 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "woocommerce_api"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["TradeGecko"]
  s.date = "2015-05-04"
  s.description = "Enables Ruby applications to communicate with the WooCommerce API."
  s.email = "support@tradegecko.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    "lib/woocommerce_api.rb",
    "lib/woocommerce_api/client.rb",
    "lib/woocommerce_api/concerns/associations.rb",
    "lib/woocommerce_api/concerns/attribute_assignment.rb",
    "lib/woocommerce_api/concerns/singleton.rb",
    "lib/woocommerce_api/resource.rb",
    "lib/woocommerce_api/resources/address.rb",
    "lib/woocommerce_api/resources/coupon.rb",
    "lib/woocommerce_api/resources/coupon_line.rb",
    "lib/woocommerce_api/resources/customer.rb",
    "lib/woocommerce_api/resources/dimensions.rb",
    "lib/woocommerce_api/resources/fee_line.rb",
    "lib/woocommerce_api/resources/image.rb",
    "lib/woocommerce_api/resources/line_item.rb",
    "lib/woocommerce_api/resources/meta.rb",
    "lib/woocommerce_api/resources/order.rb",
    "lib/woocommerce_api/resources/order_note.rb",
    "lib/woocommerce_api/resources/payment_details.rb",
    "lib/woocommerce_api/resources/product.rb",
    "lib/woocommerce_api/resources/product_review.rb",
    "lib/woocommerce_api/resources/refund.rb",
    "lib/woocommerce_api/resources/shipping_line.rb",
    "lib/woocommerce_api/resources/store.rb",
    "lib/woocommerce_api/resources/tax_line.rb",
    "lib/woocommerce_api/resources/variation.rb",
    "lib/woocommerce_api/resources/webhook.rb",
    "lib/woocommerce_api/version.rb"
  ]
  s.homepage = "http://github.com/tradegecko/woocommerce_api"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.4.5"
  s.summary = "Enables Ruby applications to communicate with the WooCommerce API"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<activemodel>, [">= 0"])
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<virtus>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<webmock>, [">= 0"])
      s.add_development_dependency(%q<vcr>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<activemodel>, [">= 0"])
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<virtus>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<webmock>, [">= 0"])
      s.add_dependency(%q<vcr>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<activemodel>, [">= 0"])
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<virtus>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<webmock>, [">= 0"])
    s.add_dependency(%q<vcr>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
  end
end
